services:
  db:
    image: motorway-test-backend
    container_name: db
    build:
      context: .
      target: motorway-test-backend
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
      - redis
    volumes:
      - /app/api/node_modules
      - ./api:/app/api
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
